In [1]:
from __future__ import division
from __future__ import print_function

%matplotlib notebook

import matplotlib.pyplot as plt
import numpy as np
import sys
from timeit import default_timer as timer

sys.path.append('/Users/ludwig/research/model_cs/cluster_model/biology_application/pcst_fast_repo')
import gslr

In [6]:
d = 8
prizes = np.zeros(d)
prizes[3] = 1.2
prizes[5] = 1.0
prizes[6] = 0.2
edges = np.transpose(np.vstack([np.arange(d - 1), np.arange(d - 1) + 1]))

n = 1000
d = 10
c = 4
sigma = 0.8


sparsity_low = 2
sparsity_high = 3
root = -1
num_clusters = 1
pruning = 'strong'
verbosity_level = 1
result, sol_vertices, sol_edges = gslr.graph_proj_sparsity(prizes, edges, sparsity_low, sparsity_high, root, num_clusters, pruning, verbosity_level)

Initial lambda_l = 7.2   lambda_r = 0.0   eps = 0.012
lambda_l = 7.2   lambda_r = 0.0   lambda_m = 3.6   cur_sparsity = 1
lambda_l = 3.6   lambda_r = 0.0   lambda_m = 1.8   cur_sparsity = 1
lambda_l = 1.8   lambda_r = 0.0   lambda_m = 0.9   cur_sparsity = 1
lambda_l = 0.9   lambda_r = 0.0   lambda_m = 0.45   cur_sparsity = 3
Returning intermediate solution for lambda_m


In [7]:
sol_vertices

array([3, 4, 5], dtype=int32)

In [8]:
sol_edges

array([4, 3], dtype=int32)

In [9]:
result

array([ 0. ,  0. ,  0. ,  1.2,  0. ,  1. ,  0. ,  0. ])